global using Microsoft.AspNetCore.Mvc;
global using Moq;
global using Progi.Test.Contracts.ServiceLibrary.Params;
global using Progi.Test.ServiceLibrary;
global using Progi.Test.ServiceLibrary.Dto;
global using Progi.Test.ServiceLibrary.Interfaces;
global using Progi.Test.WebApi.Controllers;
global using System.Threading.Tasks;
global using Xunit;
